# Generated by Django 4.2 on 2023-04-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
    ]
