# Generated by Django 4.2 on 2023-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_character_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('episode', models.CharField(max_length=10)),
                ('characters', models.ManyToManyField(related_name='episodes', to='App.character')),
            ],
        ),
    ]
